version: "3.7"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: symfony-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      #- ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - postgres
      - minio
    networks:
      - symfony-network

  php-fpm:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: symfony-php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/app
    networks:
      - symfony-network

  postgres:
    image: postgres:latest
    container_name: symfony-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql@14/data
    restart: always
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - symfony-network

  postgres-test:
    image: postgres:latest
    container_name: symfony-postgres-test
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql@14/data
    restart: always
    environment:
      POSTGRES_DB: symfony_test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    networks:
      - symfony-network

  redis:
    image: redis:7-alpine
    container_name: symfony-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/redis:/var/lib/redis/data
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - symfony-network

  minio:
    image: docker.io/bitnami/minio:latest
    container_name: symfony-minio
    ports:
      - '9009:9009'
      - '9010:9010'
    volumes:
      - ./data/minio:/bitnami/minio/data
    environment:
      MINIO_API_PORT_NUMBER: 9009
      MINIO_CONSOLE_PORT_NUMBER: 9010
      MINIO_ROOT_USER: symfony_test_bucket_access1234
      MINIO_ROOT_PASSWORD: symfony_test_bucket_secret1234
      MINIO_DEFAULT_BUCKETS: symfony-test-bucket
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge