nelmio_api_doc:
    documentation:
        info:
            title: My Symfony App
            description: Api for publishing buildings and apartments.
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]
    areas:
        path_patterns:
            - ^/api/v1/(?!/doc$)
